// <auto-generated />
using System;
using Kuva.CatalogPricing.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuva.CatalogPricing.EFMigrations.Migrations
{
    [DbContext(typeof(CatalogPricingDbContext))]
    partial class CatalogPricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.CatalogAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "CreatedAt")
                        .HasDatabaseName("IX_catalog_audit_logs_actor_id_created_at");

                    b.HasIndex("StoreId", "CreatedAt")
                        .HasDatabaseName("IX_catalog_audit_logs_store_id_created_at");

                    b.ToTable("catalog_audit_logs", "pricing");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreSkuPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreSkuPriceId");

                    b.HasIndex("StoreId", "SkuId", "ChangedAt")
                        .HasDatabaseName("IX_price_history_store_id_sku_id_changed_at");

                    b.ToTable("price_history", "pricing");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_products_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_products_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_products_status");

                    b.ToTable("products", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Impressao fotografica em papel fotografico",
                            Name = "Foto impressa",
                            ProductType = "PHOTO_PRINT",
                            RowVersion = new byte[0],
                            Slug = "foto-impressa",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_product_categories_slug");

                    b.ToTable("product_categories", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Impressao fotografica",
                            Slug = "impressao-fotografica"
                        });
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_product_variants_product_id");

                    b.ToTable("product_variants", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acb5f4a9-35fb-406a-a020-9bc5aaffa8c4"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 10x15 cm",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33c2e1f8-4e9a-4771-8f43-6e0c19bf2ed0"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 13x18 cm",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("41de4db1-31a2-4cbf-9e20-7083ba6f8ac5"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 15x21 cm",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_skus_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_skus_product_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_skus_status");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("IX_skus_variant_id");

                    b.ToTable("skus", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb454a3f-c8fd-462f-8b86-5855c71ef573"),
                            Code = "FOTO-10X15-BRILHO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 10x15 cm - BRILHO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 1,
                            Status = 1,
                            VariantId = new Guid("acb5f4a9-35fb-406a-a020-9bc5aaffa8c4")
                        },
                        new
                        {
                            Id = new Guid("4ca128f5-c7f4-4366-85d3-f4400f973b63"),
                            Code = "FOTO-10X15-FOSCO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 10x15 cm - FOSCO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 1,
                            Status = 1,
                            VariantId = new Guid("acb5f4a9-35fb-406a-a020-9bc5aaffa8c4")
                        },
                        new
                        {
                            Id = new Guid("8104052d-5abd-4f7d-a225-9d691e71f30e"),
                            Code = "FOTO-13X18-BRILHO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 13x18 cm - BRILHO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 2,
                            Status = 1,
                            VariantId = new Guid("33c2e1f8-4e9a-4771-8f43-6e0c19bf2ed0")
                        },
                        new
                        {
                            Id = new Guid("1334ef2a-c20f-49ea-9b27-3e76998f2588"),
                            Code = "FOTO-13X18-FOSCO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 13x18 cm - FOSCO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 2,
                            Status = 1,
                            VariantId = new Guid("33c2e1f8-4e9a-4771-8f43-6e0c19bf2ed0")
                        },
                        new
                        {
                            Id = new Guid("7dd70b64-d8d0-406c-8332-1bd4a56a4473"),
                            Code = "FOTO-15X21-BRILHO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 15x21 cm - BRILHO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 3,
                            Status = 1,
                            VariantId = new Guid("41de4db1-31a2-4cbf-9e20-7083ba6f8ac5")
                        },
                        new
                        {
                            Id = new Guid("3b3e2c02-7107-4361-8ad9-ff57dc8ebbd1"),
                            Code = "FOTO-15X21-FOSCO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Foto 15x21 cm - FOSCO",
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RowVersion = new byte[0],
                            SortOrder = 3,
                            Status = 1,
                            VariantId = new Guid("41de4db1-31a2-4cbf-9e20-7083ba6f8ac5")
                        });
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.SkuAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("IX_sku_attributes_sku_id");

                    b.ToTable("sku_attributes", "pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e198952-6b47-4ce3-a5cc-d14d911efa02"),
                            AttributeName = "width",
                            AttributeValue = "10",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("cb454a3f-c8fd-462f-8b86-5855c71ef573"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("6e8813de-59b4-423b-bd00-0d01c9ff1ee2"),
                            AttributeName = "height",
                            AttributeValue = "15",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("cb454a3f-c8fd-462f-8b86-5855c71ef573"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("c001bdfe-1473-4e8f-9814-16bb2697cd9b"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("cb454a3f-c8fd-462f-8b86-5855c71ef573"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("ad7c2170-4b62-4703-ae9b-b4a0c026bd4e"),
                            AttributeName = "finish",
                            AttributeValue = "brilho",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("cb454a3f-c8fd-462f-8b86-5855c71ef573"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("e1459915-728f-47a4-b747-c7a3bf9af0f9"),
                            AttributeName = "width",
                            AttributeValue = "10",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("4ca128f5-c7f4-4366-85d3-f4400f973b63"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("5e73cac3-7091-418e-81b2-71ca5947e37e"),
                            AttributeName = "height",
                            AttributeValue = "15",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("4ca128f5-c7f4-4366-85d3-f4400f973b63"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("2b2ca25a-4884-4a94-b705-f033a865743a"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("4ca128f5-c7f4-4366-85d3-f4400f973b63"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("e9583566-bb35-4eb6-9c5b-ba46b2f46887"),
                            AttributeName = "finish",
                            AttributeValue = "fosco",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("4ca128f5-c7f4-4366-85d3-f4400f973b63"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("5e5af714-2846-4784-80c0-7a4fa6c7fef8"),
                            AttributeName = "width",
                            AttributeValue = "13",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("8104052d-5abd-4f7d-a225-9d691e71f30e"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("2d6dda52-9561-41cf-afce-ff1606545e0c"),
                            AttributeName = "height",
                            AttributeValue = "18",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("8104052d-5abd-4f7d-a225-9d691e71f30e"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("86f710ba-e399-47af-82ea-b99961151396"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("8104052d-5abd-4f7d-a225-9d691e71f30e"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("7a65925e-f335-4e9d-89dd-13fa67ce384a"),
                            AttributeName = "finish",
                            AttributeValue = "brilho",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("8104052d-5abd-4f7d-a225-9d691e71f30e"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("f7eda4e5-df7d-44a0-858d-9904660ff374"),
                            AttributeName = "width",
                            AttributeValue = "13",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("1334ef2a-c20f-49ea-9b27-3e76998f2588"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("9386dce9-5cb4-4682-86bf-2aa48fc39a08"),
                            AttributeName = "height",
                            AttributeValue = "18",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("1334ef2a-c20f-49ea-9b27-3e76998f2588"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("79df32f8-50a8-4b9f-8b19-b8d8a3191fdb"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("1334ef2a-c20f-49ea-9b27-3e76998f2588"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("f41c17ab-fcda-43b1-8d4a-1f99f09aad20"),
                            AttributeName = "finish",
                            AttributeValue = "fosco",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("1334ef2a-c20f-49ea-9b27-3e76998f2588"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("8176baf1-7fe0-4b88-af64-f1c72b6fa57b"),
                            AttributeName = "width",
                            AttributeValue = "15",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("7dd70b64-d8d0-406c-8332-1bd4a56a4473"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("3c748606-0c57-457f-aa75-2c2c9749bdbd"),
                            AttributeName = "height",
                            AttributeValue = "21",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("7dd70b64-d8d0-406c-8332-1bd4a56a4473"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("7b1cd0a3-5d5e-41d2-a7cf-c5dba2b07d0e"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("7dd70b64-d8d0-406c-8332-1bd4a56a4473"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("4426c0a6-9c70-40e0-9972-503e72639e89"),
                            AttributeName = "finish",
                            AttributeValue = "brilho",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("7dd70b64-d8d0-406c-8332-1bd4a56a4473"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a18a2ec1-d16c-4c24-acfd-7f54daf9cfb0"),
                            AttributeName = "width",
                            AttributeValue = "15",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("3b3e2c02-7107-4361-8ad9-ff57dc8ebbd1"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a4413521-155c-44e5-bb3a-f5974a32dbb2"),
                            AttributeName = "height",
                            AttributeValue = "21",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("3b3e2c02-7107-4361-8ad9-ff57dc8ebbd1"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("61801972-8754-4de5-8c69-ef60502588eb"),
                            AttributeName = "unit",
                            AttributeValue = "cm",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("3b3e2c02-7107-4361-8ad9-ff57dc8ebbd1"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("10bff357-a96b-4bff-a156-7f7c508acdfb"),
                            AttributeName = "finish",
                            AttributeValue = "fosco",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SkuId = new Guid("3b3e2c02-7107-4361-8ad9-ff57dc8ebbd1"),
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.StoreSkuPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("IX_store_sku_prices_sku_id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_store_sku_prices_store_id");

                    b.HasIndex("StoreId", "SkuId", "Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_store_sku_prices_store_id_sku_id_status_valid_from_valid_to");

                    b.ToTable("store_sku_prices", "pricing");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.PriceHistory", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.StoreSkuPrice", "StoreSkuPrice")
                        .WithMany("History")
                        .HasForeignKey("StoreSkuPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreSkuPrice");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Product", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.ProductVariant", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Sku", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuva.CatalogPricing.Entities.ProductVariant", "Variant")
                        .WithMany("Skus")
                        .HasForeignKey("VariantId");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.SkuAttribute", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.Sku", "Sku")
                        .WithMany("Attributes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.StoreSkuPrice", b =>
                {
                    b.HasOne("Kuva.CatalogPricing.Entities.Sku", "Sku")
                        .WithMany("Prices")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Product", b =>
                {
                    b.Navigation("Skus");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.ProductVariant", b =>
                {
                    b.Navigation("Skus");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.Sku", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Kuva.CatalogPricing.Entities.StoreSkuPrice", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
